[package]
name = "pallet-otc-claim"
version = "0.1.0"
edition = "2021"
license = "MIT-0"

[dependencies]
scale-info = { workspace = true, default-features = false, features = ["derive"] }
codec = { workspace = true, default-features = false, features = ["derive"] }
sp-std = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
byte-slice-cast = { version = "1.2", default-features = false }

[features]
default = ["std"]
std = [
  "scale-info/std",
  "codec/std",
  "sp-std/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-io/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-balances/std",
  "byte-slice-cast/std",
]

